/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.cruftbusters.ktor_starter_v2.zip_starter

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}
